### ISSUE TITLE
Responsive navigation

### ISSUE THREAD

**Issue by vebam** [n33/baseline#5]
Hello,
Is there a simple way to responsive nav, but as herein:
http://html5up.net/uploads/demos/twenty/

With wide screen normal navigation
with mobile screen Off-canvas

**Comment by yomli** [comment]
Yes, there is a way. Version 2 of Skel Baseline was like that, so you can either take a look at it or wait for anyone willing to recreate it in version 3. 

I'm currently trying to make the nav responsive **and** working without javascript (CSS fallback in case of disabled js) for a project of mine, but it's not my top priority so don't expect a quick answer.

But just for the responsive nav, you can do it in 2 steps :
- Moving the `nav` block inside the `header` :

``` HTML
        <!-- Header -->
            <header id="header">
                <h1><a href="#">Baseline</a></h1>
                <a href="#">Login</a>
                <a href="#nav">Menu</a>
                <!-- Nav -->
                <nav id="nav">
                    <ul class="links">
                        <li><a href="#top">Top</a></li>
                        <li><a href="#content">Content</a></li>
                        <li><a href="#elements">Elements</a></li>
                        <li><a href="#grid">Grid System</a></li>
                    </ul>
                    <ul class="actions vertical">
                        <li><a href="http://skel.io" class="button special fit">Download</a></li>
                        <li><a href="http://skel.io" class="button fit">Documentation</a></li>
                    </ul>
                </nav>
            </header>
```
- A little CSS magic :

``` CSS
/* Needed since we moved the nav block inside the header */
#nav {
    text-align: left;
}
/* We hide the Menu link on wide screen */
#header > a[href="#nav"] {
    display:none;
}
/* And we display it on small screen */
@media screen and (max-width: 736px) {
    #header > a[href="#nav"] {
        display:inline-block;
    }
}
/* Lastly, we display the nav like a good old inline menu on wide screen */
@media screen and (min-width: 737px) {
    #nav {
        -moz-transform: translateX(0em);
        -webkit-transform: translateX(0em);
        -ms-transform: translateX(0em);
        transform: translateX(0em);
        background: transparent;
        box-shadow: none;
        color: #ffffff;
        line-height: 3.25em;
        height:3.25em;
        max-width: 80%;
        overflow-y: hidden;
        padding: 0;
        position: static;
        float:right;
        visibility: visible;
        width: auto;
        line-height: 3.25em;
    }

    #nav .close {
        display:none;
    }

    #nav ul li,
    #nav ul,
    #nav {
        display: inline-block;
        margin:0;
        padding:0;
    }

    #nav > ul.links > li > a:not(.button) {
            -moz-transition: color 0.2s ease-in-out;
            -webkit-transition: color 0.2s ease-in-out;
            -ms-transition: color 0.2s ease-in-out;
            transition: color 0.2s ease-in-out;
            display: inline-block;
            padding: 0 0.75em;
            color: #d5d5d5;
            text-decoration: none;
            border-top: 0 !important;
            line-height: 3.25em;
            height:3.25em;
        }

    #nav > ul.links > li > a:not(.button):hover {
        color: #ffffff;
    }

    #nav > ul.links > li > .button {
        display:inline-block;
    }
}
```

Result:
 [![Baseline Wide](http://i.imgur.com/7BJAuI4.jpg)](http://imgur.com/7BJAuI4)
 [![Baseline Small](http://i.imgur.com/SbaOCDM.jpg)](http://imgur.com/SbaOCDM)

It's just a raw sketch made in less than 10min, so feel free to edit it to match your project.
